# Generated by Django 4.2.7 on 2025-08-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "api_name",
                    models.CharField(max_length=100, verbose_name="API название"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("deepseek", "DeepSeek"),
                        ],
                        max_length=50,
                        verbose_name="Провайдер",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "AI Модель",
                "verbose_name_plural": "AI Модели",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Assistant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("prompt", models.TextField(verbose_name="Системный промпт")),
                ("role", models.TextField(blank=True, verbose_name="Роль")),
                ("task", models.TextField(blank=True, verbose_name="Задача")),
                (
                    "task_description",
                    models.TextField(blank=True, verbose_name="Описание задачи"),
                ),
                ("rules", models.TextField(blank=True, verbose_name="Правила")),
                (
                    "key_references",
                    models.TextField(blank=True, verbose_name="Ключевые ссылки"),
                ),
                ("criteria", models.TextField(blank=True, verbose_name="Критерии")),
                (
                    "evaluation_rubric",
                    models.TextField(blank=True, verbose_name="Рубрика оценивания"),
                ),
                (
                    "explicit_reminders",
                    models.TextField(blank=True, verbose_name="Явные напоминания"),
                ),
                (
                    "rule_additional_privacy",
                    models.TextField(
                        blank=True, verbose_name="Дополнительные правила приватности"
                    ),
                ),
                (
                    "additional_guidelines",
                    models.TextField(
                        blank=True, verbose_name="Дополнительные руководящие принципы"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Ассистент",
                "verbose_name_plural": "Ассистенты",
                "ordering": ["order", "name"],
            },
        ),
    ]
