# Generated by Django 4.2.7 on 2025-08-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic"),
                    ("deepseek", "DeepSeek"),
                    ("google", "Google"),
                ],
                max_length=50,
                verbose_name="Провайдер",
            ),
        ),
    ]
